accounts:
  - name: alice
    coins: ["100000000uusdtpe", "10000000000000000000uMGT"]
  - name: bob
    coins: ["5000000000000uusdtpe"]
validator:
  name: alice
  staked: "100000000000000000000uusdtpe"
faucet:
  name: bob 
  coins: ["10uusdtpe"]
build:
  binary: "usdtped"
init:
  home: "$HOME/.usdtped"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "FCO_9000-1"
  app_state:
    staking:
      params:
        bond_denom: "uusdtpe"
    mint:
      params:
        mint_denom: "uusdtpe"
    crisis:
      constant_fee:
        denom: "uusdtpe"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "uusdtpe"
    evm:
      params:
        evm_denom: "uusdtpe"
